apiVersion: v1
kind: Secret
metadata:
  name: my-registry-key
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    # Ce secret sera créé par le script ou Jenkins
    # Il contiendra les credentials Docker Hub encodés en base64
